export const labels = {
  product: 'Wybierz produkt:',
  box: 'Wybierz opakowanie:',
  ammount: 'Liczba opakowań:',
  delivery: 'Sposób dostawy:',
  delName: 'Dostawa - Nazwa',
  delCity: 'Dostawa - Miasto:',
  delPostCode: 'Dostawa - Kod Pocztowy:',
  delStreet: 'Dostawa - Ulica:',
  payment: 'Sposób zapłaty:',
  invoice: 'Faktura:',
  fvName: 'Faktura - Nazwa:',
  nip: 'Faktura - NIP:',
  fvCity: 'Faktura - Miasto:',
  fvPostCode: 'Faktura - Kod Pocztowy:',
  fvStreet: 'Faktura - Ulica:',
  notes: 'Uwagi dodatkowe:',
  phone: 'Numer telefonu:',
  email: 'E-mail:'
};
