export const labels = {
  product: 'Wybierz produkt:',
  box: 'Wybierz opakowanie:',
  ammount: 'Liczba opakowań:',
  delivery: 'Sposób dostawy:',
  delName: 'Nazwa',
  delCity: 'Miasto:',
  delPostCode: 'Kod Pocztowy:',
  delStreet: 'Ulica:',
  payment: 'Sposób zapłaty:',
  invoice: 'Faktura:',
  fvName: 'Nazwa:',
  nip: 'NIP:',
  fvCity: 'Miasto:',
  fvPostCode: 'Kod Pocztowy:',
  fvStreet: 'Ulica:',
  notes: 'Uwagi dodatkowe:',
  phone: 'Numer telefonu:',
  email: 'E-mail:',
  productCost: 'Wartość zamówienia:',
  deliveryCost: 'Szacowana cena dostawy:',
  totalCost: 'Razem:',
  transferDetails: 'Dane do przelewu:'
};
